In [1]:
import pandas as pd

In [2]:
files = ['test_00.json', 'test_01.json', 'test_02.json', 'test_03.json', 'test_04.json', 'test_05.json', 'test_06.json', 'test_07.json', 'test_08.json', 'test_09.json']
texts = []
answers = []
targets = []
f = []
for filename in files:
    file = pd.read_json(f'{filename}')
    f.append(file)

In [3]:
#!cat test_02.json

In [4]:
# here making a list of all tasks from all the files
tasks = []
for i in range(len(f)):
    task = f[i]['tasks']
    for j in range(len(task[i])):
        task = f[i]['tasks'][j]
        tasks.append(task)

In [5]:
# filtering the tasks,which we need
needed_tasks = []
for i in range(len(tasks)):
    if ('ГЛАВНАЯ' or 'главная') in tasks[i]['text']:
        needed_tasks.append(tasks[i])

In [6]:
zad_txt =[]
otv_txt= []
solutions = []
otv_ch = []
targets = []
task_nb = []
for i in range(len(needed_tasks)):
    for j in range(len(needed_tasks[i]['question']['choices'])):
        otv_txt.append(needed_tasks[i]['question']['choices'][j]['text'])
        zad_txt.append(needed_tasks[i]['text'])
        target = needed_tasks[i]['solution']['correct_variants'][0]
        solutions.append(target)
        targets.append(1 if needed_tasks[i]['question']['choices'][j]['id'] in target else 0)
        task_nb.append(i+1)

In [7]:
for i in range(len(zad_txt)):
    f = zad_txt[i].find('(')
    zad_txt[i] =zad_txt[i][f:]

In [8]:
task_series = pd.Series(task_nb)
target_series = pd.Series(targets)
#sol_series = pd.Series(solutions)
zad_series = pd.Series(zad_txt)
otv_series = pd.Series(otv_txt)
frame = {'Task №':task_series ,'Task text': zad_series, 'Answers': otv_series, 'Target':target_series}
result_df=pd.DataFrame(frame)
result_df

,Task №,Task text,Answers,Target
0,1,(1)Один греческий историк по праву назвал Егип...,"1) На берегах Нила всегда селились египтяне,...",1
1,1,(1)Один греческий историк по праву назвал Егип...,2) Египтяне всегда селились на узких полосах з...,0
2,1,(1)Один греческий историк по праву назвал Егип...,"3) Египет по праву назвали «даром Нила», так к...",1
3,1,(1)Один греческий историк по праву назвал Егип...,4) Один греческий историк по праву назвал Егип...,0
4,1,(1)Один греческий историк по праву назвал Егип...,5) Египет стал колыбелью второй великой цивили...,0
5,2,(1)В некоторых моделях современных автомобилей...,1) Современные автомобили очень часто оснащают...,0
6,2,(1)В некоторых моделях современных автомобилей...,2) В некоторых современных автомобилях раскрыт...,1
7,2,(1)В некоторых моделях современных автомобилей...,"3) Подушки безопасности, часто используемые в ...",0
8,2,(1)В некоторых моделях современных автомобилей...,4) В некоторых моделях автомобилей невозможно ...,0
9,2,(1)В некоторых моделях современных автомобилей...,5) Срабатывание подушек уже само по себе может...,1
10,3,(1) Термин «новая история» появился в европейс...,Новой историей мыслители-гуманисты называли эп...,0
11,3,(1) Термин «новая история» появился в европейс...,"Понятие «новая история», предложенное мыслител...",1
12,3,(1) Термин «новая история» появился в европейс...,Мыслители-гуманисты эпохи Возрождения предложи...,0
13,3,(1) Термин «новая история» появился в европейс...,"Значение термина «новая история», возникшего в...",1
14,3,(1) Термин «новая история» появился в европейс...,Понятие «новая история» возникло в трудах мысл...,0
15,4,"(1) Притча, как известно, пришла в русскую лит...",Притча как жанр появилась в русской литературе...,0
16,4,"(1) Притча, как известно, пришла в русскую лит...",Массовый интерес учёных к притче – древнейшему...,0
17,4,"(1) Притча, как известно, пришла в русскую лит...",Несмотря на то что жанр притчи является очень ...,1
18,4,"(1) Притча, как известно, пришла в русскую лит...",В последнем десятилетии прошлого века был опуб...,0
19,4,"(1) Притча, как известно, пришла в русскую лит...",Широкий интерес литературной критики к древнем...,1
20,5,(1) Вулканическая магма состоит из многих комп...,1) Магма состоит из многих компонентов: кальци...,0
21,5,(1) Вулканическая магма состоит из многих комп...,2) Количество главного компонента магмы — окис...,1
22,5,(1) Вулканическая магма состоит из многих комп...,3) Существует множество вулканов различных фор...,0
23,5,(1) Вулканическая магма состоит из многих комп...,4) От количества некоторых элементов зависят с...,0
24,5,(1) Вулканическая магма состоит из многих комп...,"5) От количества окиси кремния, являющейся гла...",1
25,6,(1)Построенный по приказу Людовика XIV Версаль...,"1) Версальский дворец, символизирующий величие...",0
26,6,(1)Построенный по приказу Людовика XIV Версаль...,"2) Министр финансов Франции Николя Фуке, фавор...",0
27,6,(1)Построенный по приказу Людовика XIV Версаль...,3) Версальский дворец обязан своим появлением ...,1
28,6,(1)Построенный по приказу Людовика XIV Версаль...,4) В 1661 году министр финансов Франции Николя...,0
29,6,(1)Построенный по приказу Людовика XIV Версаль...,5) После посещения замка министра финансов Фук...,1
30,7,(1)Почти все используемые нами материалы произ...,"1) Материалы, используемые человеком, производ...",0
31,7,(1)Почти все используемые нами материалы произ...,"2) Нефть, дерево, хлопок и многие другие матер...",0
32,7,(1)Почти все используемые нами материалы произ...,3) Первичная материя — это непереработанные ма...,1
33,7,(1)Почти все используемые нами материалы произ...,"4) Пластик получают из нефти, бумагу — из дере...",0
34,7,(1)Почти все используемые нами материалы произ...,5) Для производства и получения различных мат...,1
35,8,(1)Закаливание — это тренировка и совершенство...,"1) Закаливающие процедуры, которые помогают че...",0
36,8,(1)Закаливание — это тренировка и совершенство...,2) Закаливание — это систематическая активная ...,1
37,8,(1)Закаливание — это тренировка и совершенство...,3) Тренировки проводятся в целях уравновешиван...,0
38,8,(1)Закаливание — это тренировка и совершенство...,4) Закаливающие процедуры должны быть постепен...,0
39,8,(1)Закаливание — это тренировка и совершенство...,5) Для повышения работоспособности и устойчиво...,1

In [9]:
result_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 4 columns):
Task №       40 non-null int64
Task text    40 non-null object
Answers      40 non-null object
Target       40 non-null int64
dtypes: int64(2), object(2)
memory usage: 1.4+ KB

In [10]:
pasti = 0 
l_answer = []
l_questions = []
for each in result_df.itertuples(): # each is a tuple with 5 values: index,task nb,text,answer and target
    ind = each[1]
    question = each[2]
    ans = each[3]
    q_words = question.split(' ') # make a list from text 
    ans_words = ans.split(' ')   # list for answers
    ans_words_with_ind = [ind,ans_words]
    if pasti == ind:
        l_answer.append(ans_words_with_ind) 
    else:
        l_answer.append(ans_words_with_ind) 
        l_questions.append(q_words)
    pasti = ind

In [11]:
corrected_q =[] # очистка от дополнительных знаков 
for i in range(len(l_questions)):
    question = l_questions[i]
    q = []
    for each in question:
        if '1' in each:
            each = each.replace('1','')
        if '2' in each:
            each = each.replace('2','')
        if '3' in each:
            each = each.replace('3','')
        if ',' in each:
            each = each.replace(',','')
        if '.' in each:
            each = each.replace('.','')
        if '«' in each:
            each = each.replace('«','')
        if '»' in each:
            each = each.replace('»','')
        if '(' in each:
            each = each.replace('(','')
        if ')' in each:
            each = each.replace(')','')
        if '”' in each:
            each = each.replace('”','')
        if '"' in each:
            each = each.replace('"','')
        if '“' in each:
            each = each.replace('“','')            
        if '\xa01' in each:
            each = each.replace('\xa01',' ')
            pos = each.find(' ')
            each = each[:pos]
        if '<' in each:
            each = each.replace('<','')
        if '>' in each:
            each = each.replace('>','')
        each = each.lower()
        if len(each) >= 4:
            q.append(each)
    corrected_q.append(q)

In [12]:
corrected_a =[] # очистка от дополнительных знаков 
for i in range(len(l_answer)):
    answer = l_answer[i][1]
    a = []
    for each in answer:
        if '1' in each:
            each = each.replace('1','')
        if '2' in each:
            each = each.replace('2','')
        if '3' in each:
            each = each.replace('3','')
        if ',' in each:
            each = each.replace(',','')
        if '.' in each:
            each = each.replace('.','')
        if '«' in each:
            each = each.replace('«','')
        if '»' in each:
            each = each.replace('»','')
        if '(' in each:
            each = each.replace('(','')
        if ')' in each:
            each = each.replace(')','')
        if '”' in each:
            each = each.replace('”','')
        if '"' in each:
            each = each.replace('"','')
        if '“' in each:
            each = each.replace('“','')            
        if '\xa01' in each:
            each = each.replace('\xa01',' ')
            pos = each.find(' ')
            each = each[:pos]
        if '<' in each:
            each = each.replace('<','')
        if '>' in each:
            each = each.replace('>','')
        each = each.lower()
        if len(each) >= 4:
            a.append(each)
    a =[i//5 +1, a]
    corrected_a.append(a)

In [13]:
intersections = []
differences = []

In [14]:
ans_words = corrected_a
text_words = corrected_q

In [15]:
differences = []
intersections = []

for i in range(len(ans_words)):
    diff = 0
    inter = 0
    for word in ans_words[i][1]:
        if word in text_words[ans_words[i][0]-1]:
            inter +=1
        else:
            diff += 1
    intersections.append(inter)
    differences.append(diff)
    
col1 = pd.Series(intersections)
col2 = pd.Series(differences)

In [16]:
result_df['intersection'] = col1
result_df['difference'] = col2

In [17]:
len(corrected_a),len(corrected_q)

(40, 8)

In [18]:
from sklearn import preprocessing
le_q = preprocessing.LabelEncoder()
le_a = preprocessing.LabelEncoder()

list_questions =[]
list_answers =[]

for i in range(40):
    one_ans =result_df['Answers'][i]
    list_answers.append(one_ans)

for i in range(8):
    one_ques =result_df['Task text'][5*i]
    list_questions.append(one_ques)

le_a.fit(list_answers)
le_q.fit(list_questions)

len(list_answers),len(list_questions)
tr_q = le_q.transform(result_df['Task text'])
tr_a = le_a.transform(result_df['Answers'])

result_df['Task text'] = tr_q
result_df['Answers'] = tr_a

In [19]:
X = result_df.drop(['Target','Task text','Answers','Task №'],axis =1)
y = result_df.Target

In [20]:
X

    intersection  difference
0             16           8
1             14           2
2             14           8
3             13           3
4              8          10
5              2          13
6             14           7
7              7           8
8              6           5
9             16           8
10            11           9
11            11          13
12            12           5
13            11           7
14            16           5
15            11          18
16             7          12
17             9          22
18            11          13
19            19          13
20            15           1
21             6           6
22             1           6
23             6           5
24             9           5
25            12           6
26            18           8
27            13           9
28            18           7
29            11          14
30             6           1
31             7           5
32             5           5
33             6           3
34             3          10
35             8           8
36            13           7
37             0          10
38             8           1
39            13          10

In [21]:
import numpy as np
from sklearn.model_selection import GroupKFold
groups = []
for i in range(1,9):
    groups += [i]*5
groups = np.array(groups)
group_kfold = GroupKFold(n_splits=8)

In [22]:
groups

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8])

In [23]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100,random_state=0)
from sklearn.model_selection import cross_val_score

In [24]:
n = cross_val_score(clf, X, y ,groups = groups,cv = group_kfold)

In [25]:
print(n)
print('Mean =',np.mean(n),'; Max = ',np.max(n))#Min = ',np.min(n))
# results of cross validation

[1.  0.6 0.6 0.6 0.6 0.4 1.  1. ]
Mean = 0.725 ; Max =  1.0

In [26]:
# trying to predict, splitting into train and test 
for train_index, test_index in group_kfold.split(X, y, groups):
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [27]:
clf.fit(X_train,y_train)
clf.predict(X_test)

array([1, 0, 1, 0, 0])

In [28]:
from sklearn.metrics import roc_auc_score
print('Train score = ',roc_auc_score(y_train, clf.predict(X_train)))
print('Test score = ',roc_auc_score(y_test, clf.predict(X_test)))

Train score =  0.9761904761904762
Test score =  1.0